### ISSUE TITLE
Is this different from dhcdrop?

### ISSUE THREAD

**Issue by vi** [mschwager/dhcpwn#3]
Man page: https://manned.org/dhcdrop/ca9fd8fc

**Comment by mschwager** [comment]
Hmm, they look very similar! Never heard of `dhcdrop` before. I'd imagine you could accomplish everything with `dhcdrop` that you could with `dhcpwn` (specifically with the `-F` flag).

However, `dhcpwn`'s code is probably easier on the eyes, and more prone to hacking on :)

**Comment by vi** [comment]
Primary goal of `dhcdrop` is to monitor network for rogue (e.g. misconfigured, technically not in whitelist) DHCP servers and automatically supress them. Is this supported in dhcpwn?

**Comment by mschwager** [comment]
There is a `sniff` feature (https://github.com/mschwager/dhcpwn/blob/master/dhcpwn.py#L30), but it's not very advanced. With a little bit of work I'm sure it could provide that functionality.
