### ISSUE TITLE
Error on scapy

### ISSUE THREAD

**Issue by erwinbierens** [mschwager/dhcpwn#4]
Hi,

i've some issues running the code. 
i'm running Python 2.7.9

Traceback (most recent call last):
  File "./dhcpwn.py", line 9, in <module>
    from scapy.all import *
ImportError: No module named 'scapy'

i've installed the pyhton-scapy module. Is there a solution to run the dhcpwn tool on this version of python?

regards,
Erwin

**Comment by mschwager** [comment]
Is it possible for you to run Python 3? If not you should be able to install the Python 2 version of `scapy` and change the shebang in the `dockit.py` script to be `python2` and it should work. I believe the code is still Python 2 compliant. Let me know what you find.

**Comment by erwinbierens** [comment]
changing the first line to: 
#!/usr/bin/env python2

does resolv the issue! Thx
